### ISSUE TITLE
Почему не работает на 18 nodejs?

### ISSUE THREAD

**Issue by omqmo** [yandex-cloud/serverless-plugin#106]
Как запустить serverless-yandex-cloud на nodejs18+? Не знаю, как в глобальных масштабах, но на github-actions из-за указанного пакета зависимости необходимо не устанавливать, а пересобирать с помощью команды npm rebuild. Это, как минимум, ломает nx. Разбираться в совместимости с устаревшей версией nodejs для каждой из сотен пакетов  nx,ну вообще сами понимаете никто не будет. Поэтому, вопрос - в чем проблема переписать упомянутый пакет на актуальные версии ноды?  

Если у кого-то есть рабочий пример github-actions + serverless + nx буду очень рад, если им поделитесь.

**Comment by nikolaymatrosov** [comment]
А зачем вы используете этот пакет в github actions? Есть же отдельный экшен для деплоя функции https://github.com/yc-actions/yc-sls-function

**Comment by omqmo** [comment]
@nikolaymatrosov оу, мне этот не попадался. Спасибо, сейчас попробую.

> А зачем вы используете этот пакет в github actions?  

action для нативного serverless, который также подключает плагины. Лучше я ничего не смог найти, но ваш вариант выглядит аналогичным.

**Comment by DavyJohnes** [comment]
> из-за указанного пакета зависимости необходимо не устанавливать, а пересобирать с помощью команды npm rebuild

Можно тут подробнее, пожалуйста? Помечу нельзя просто установить плагин как зависимость и использовать его, как указано в документации?
