### ISSUE TITLE
Getting metadata from plugin failed with error: failed to fetch token from metadata service

### ISSUE THREAD

**Issue by quytang-gfg** [yandex-cloud/serverless-plugin#50]
Hi,
I was testing for `lambda serverless` migration from AWS to Yandex Cloud. However, this happened when I tried to deploy with `serverless deploy`.
```
'Getting metadata from plugin failed with error: failed to fetch token from metadata service:
FetchError: request to http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token failed,
reason: connect ETIMEDOUT 169.254.169.254:80'
```
The **yc** was already set up and I can also create the cloud functions in the console UI.
Do you have any idea about it?

Thanks

**Comment by DavyJohnes** [comment]
Hi!
Which version of yandex cloud serverless plugin do you use? Please try 1.0-beta from this branch https://github.com/yandex-cloud/serverless-plugin/tree/beta

**Comment by quytang-gfg** [comment]
Hi!
I got this issue when I use the beta version.
```
Error ---------------------------------------------------
 
  Error: Token is not defined in ~/yandex-cloud/config.yaml
 ```
I wonder how to get the token because it didn't state in the docs.
I init the client with a federation account, not a Yandex ID:
`yc init --federation-id <id>`

Thanks a lot!

**Comment by DavyJohnes** [comment]
I would suggest you to use YC_TOKEN, YC_CLOUD_ID and YC_FOLDER_ID env variables.
Here is guide how to obtain token: https://cloud.yandex.com/en-ru/docs/iam/concepts/authorization/oauth-token

**Comment by quytang-gfg** [comment]
I can not get the token this way because my provided account is a federated user - https://cloud.yandex.com/en/docs/cli/operations/authentication/federated-user.
I read through the config files, and there is the iam_token. So can I use this token instead?
```
cat ~/.config/yandex-cloud/credentials/default
{
  "federation-credentials": {
    "federation-id": <federation-id>,
    "federation-endpoint": "console.cloud.yandex.ru",
    "token": {
      "iam_token": <token>,
      "expires_at": {
        "seconds": 1647524868,
        "nanos": 381000000
      }
    }
  }
}
```

**Comment by DavyJohnes** [comment]
Authorizing using iam token is not support yet, but I will add it soon. Sorry for inconvenience.

**Comment by DavyJohnes** [comment]
Check it in https://github.com/yandex-cloud/serverless-plugin/releases/tag/v1.0.0-beta.4

**Comment by quytang-gfg** [comment]
It works. Thanks a lot!
