### ISSUE TITLE
Add support of event trigger by httpApi or http event

### ISSUE THREAD

**Issue by shalumaheshwari** [yandex-cloud/serverless-plugin#52]
Hello,

I am using this plugin to trigger events for cloud functions. I would like to trigger my function using http request. Is there a plan to add this support? Or is there any alternative solution for now?

**Comment by DavyJohnes** [comment]
Hello,
I do not fully understand, to be honest. Could you please explain by example?
Is `serverless invoke ...` what you need?

**Comment by shalumaheshwari** [comment]
Hello @DavyJohnes ,  
I want to create and update http end points using API Gateway and integrate it with cloud functions. 

For reference, please refer to these:
https://www.serverless.com/framework/docs/providers/aws/events/apigateway
https://cloud.yandex.ru/docs/api-gateway/quickstart/#update

Thanks

**Comment by DavyJohnes** [comment]
Ok, I got it. I guess https://github.com/yandex-cloud/serverless-plugin/issues/8 is the same feature request.

**Comment by shalumaheshwari** [comment]
@DavyJohnes  Indeed, it's the same request.
