### ISSUE TITLE
Add support for VPC

### ISSUE THREAD

**Issue by quytang-gfg** [yandex-cloud/serverless-plugin#54]
Hi,
I tried to connect the Yandex DB from the cloud functions but it did not work.
For Postgres, it's ok because we can create a DB connection proxy. The proxy only works for Postgres and ClickHouse.

Then I have some questions
1. How to set up the VPC and subnet for the cloud functions?
2. Are there any ways to connect to other DB such as YDB, ElasticSearch, ...?

P.S. We use aws-sdk (dynamodb) for reusing the existing code base.

Thanks,

**Comment by DavyJohnes** [comment]
Hi! I would suggest you to forward this question to [Yandex Cloud support](https://cloud.yandex.com/en-ru/docs/support/overview) directly since it is actually not related to serverless framework.
