### ISSUE TITLE
Serverless deploy

### ISSUE THREAD

**Issue by scorp1k** [yandex-cloud/serverless-plugin#59]
`Environment: win32, node 16.13.2, framework 3.10.2, plugin 6.2.0, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Env variable HOME is not defined`

Error appear when I'm trying execute `serverless deploy` in template directory

**Comment by DavyJohnes** [comment]
Fixed in https://github.com/yandex-cloud/serverless-plugin/pull/60

**Comment by DavyJohnes** [comment]
@scorp1k Сейчас работает?

**Comment by scorp1k** [comment]
> @scorp1k Сейчас работает?

Данная ошибка пропала
