### ISSUE TITLE
Add support of API Gateway creation

### ISSUE THREAD

**Issue by nikolaymatrosov** [yandex-cloud/serverless-plugin#8]
It would be great if I could deploy the whole app via only one CLI command.

**Comment by nikolaymatrosov** [comment]
It would be great to support Events. So framework could automate the creation of OpenAPI spec based on serverless config YAML. It would be useful because I could use function names instead of ids that I have to use if I compose the spec by hand.

Example, of AWS events: https://www.serverless.com/framework/docs/providers/aws/guide/events
https://www.serverless.com/framework/docs/providers/aws/events/http-api

**Comment by nikolaymatrosov** [comment]
There are some changes in ApiGateway definition section in Serverless Framework v3.
https://www.serverless.com/framework/docs/guides/upgrading-v3#api-gateway

**Comment by emahota-flo** [comment]
@DavyJohnes 
Any updates on this topic?

**Comment by DavyJohnes** [comment]
> @DavyJohnes
> Any updates on this topic?

Not yet, unfortunately. I believe I'll be able to start work this in next 2 weeks.
